FIX: Allow CWL templates to build correctly
qiime2/q2cwl pull request #11
Opened 2020-02-11 21:48 UTC by David-Rod

This PR should fix issue #9. 

- Make file is updated to include the new target
- Make file command `cwl-runner` has been updated to `cwltool`
- New directory for `confusion-matrix`
  - Includes new `job.yaml` file
- Update for `template.py` that handles primitive unions for CWL template building

2020-02-11 21:50 UTC, David-Rod commented
@ebolyen I will hold off on assigning this to a project until after the 2020.2 release, unless you would like this to be squeezed in?

2020-02-13 16:11 UTC, ebolyen requested changes
Looking pretty good, just need to generalize the logic a little bit.

2020-02-13 16:11 UTC, ebolyen commented on examples/confusion-matrix/job.yaml
> +outputs:
We can drop this section.

2020-02-13 16:11 UTC, ebolyen commented on q2cwl/template.py
> +    elif qiime_type.to_ast()['members'][0]['name'] in CWL_MAP.keys() and \
We want to verify that this is a union before destructuring it.

2020-02-13 16:11 UTC, ebolyen commented on q2cwl/template.py
> +                        CWL_MAP[union_members[1]['name']]
This list should probably be made with a for-loop.

2020-02-13 16:11 UTC, ebolyen commented on q2cwl/template.py
> +                'default': 'auto',
We can't hardcode this part.

2020-02-13 16:11 UTC, ebolyen commented on q2cwl/template.py
> +                'default': 'auto',
use the `default` variable already defined above

2020-02-13 20:20 UTC, ebolyen approved these changes
Looks good, thank you @David-Rod!

2020-02-13 20:21 UTC, merged